In [3]:
import pandas as pd 

df = pd.read_csv('diamonds.csv',index_col = 0)
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [4]:
df['cut'].unique()

array(['Ideal', 'Premium', 'Good', 'Very Good', 'Fair'], dtype=object)

In [7]:
#df['cut'].astype('category').cat.codes 
#for classification

In [8]:
cut_class_dict = {"Fair":1,"Good":2,"Very Good":3,"Premium":4,"Ideal":5}
clarity_dict = {"I3": 1, "I2": 2, "I1": 3, "SI2": 4, "SI1": 5, "VS2": 6, "VS1": 7, "VVS2": 8, "VVS1": 9, "IF": 10, "FL": 11}
color_dict = {"J": 1,"I": 2,"H": 3,"G": 4,"F": 5,"E": 6,"D": 7}

df['cut'] = df['cut'].map(cut_class_dict)
df['clarity'] = df['clarity'].map(clarity_dict)
df['color'] = df['color'].map(color_dict)

df.head()

   carat  cut  color  clarity  depth  table  price     x     y     z
1   0.23    5      6        4   61.5   55.0    326  3.95  3.98  2.43
2   0.21    4      6        5   59.8   61.0    326  3.89  3.84  2.31
3   0.23    2      6        7   56.9   65.0    327  4.05  4.07  2.31
4   0.29    4      2        6   62.4   58.0    334  4.20  4.23  2.63
5   0.31    2      1        4   63.3   58.0    335  4.34  4.35  2.75

In [15]:
import sklearn
from sklearn import svm,preprocessing
#good idea to shuffle the model
df = sklearn.utils.shuffle(df)
df.head()

       carat  cut  color  clarity  depth  table  price     x     y     z
28767   0.31    5      6        6   61.9   55.0    680  4.34  4.38  2.70
18543   1.47    4      4        4   61.8   58.0   7557  7.28  7.22  4.48
13922   1.02    5      3        6   62.4   57.0   5666  6.40  6.35  3.98
35063   0.30    5      7        7   61.1   57.0    885  4.34  4.37  2.66
19488   1.14    5      4        7   61.8   55.0   8121  6.71  6.76  4.16

In [16]:
#now assign value for x and y for ML
x = df.drop('price',axis = 1).values
x = preprocessing.scale(x)
y = df['price'].values

test_size = 200

x_train = x[:-test_size]
y_train = y[:-test_size]

x_test = x[-test_size:]
y_test = y[-test_size:]

clf = svm.SVR(kernel = 'linear')
clf.fit(x_train,y_train)

SVR(kernel='linear')

In [17]:
clf.score(x_test,y_test)

0.8412311396737147

In [18]:
for x,y in zip(x_test,y_test):
    print(f'Model: {clf.predict([x])[0]},Actual: {y}')

Model: 1965.4490135152992,Actual: 1882
Model: 8025.834255197804,Actual: 7730
Model: 2120.932259468582,Actual: 2012
Model: 5102.82792783404,Actual: 7258
Model: 1914.3788127126545,Actual: 1721
Model: 1496.9857791840113,Actual: 953
Model: 4963.392867840926,Actual: 5420
Model: 541.8436073547527,Actual: 907
Model: 8457.830935697511,Actual: 9193
Model: -49.5414254032321,Actual: 698
Model: 5747.366970168061,Actual: 3665
Model: 7133.549517466368,Actual: 8652
Model: 2474.7523006429756,Actual: 2052
Model: 59.191988898854106,Actual: 584
Model: 679.829359289477,Actual: 533
Model: 302.37069771022925,Actual: 567
Model: 2333.9176324740224,Actual: 1869
Model: 3941.6175287032165,Actual: 3459
Model: 9766.125235015386,Actual: 9510
Model: 9774.15230142644,Actual: 14593
Model: 4066.5065287665557,Actual: 4080
Model: 1563.2488063593246,Actual: 1370
Model: 1984.3016801978292,Actual: 1657
Model: 6909.753043336068,Actual: 9931
Model: 693.0839633750925,Actual: 764
Model: -24.74329133970923,Actual: 663
Model: 5288.7854752062885,Actual: 4816
Model: 252.04932741642097,Actual: 743
Model: -557.8475684771697,Actual: 540
Model: 8314.519059861157,Actual: 11655
Model: 5153.899829179669,Actual: 5096
Model: 3731.8066759383996,Actual: 3153
Model: 26.992045238953324,Actual: 672
Model: 2763.640897106733,Actual: 2528
Model: 110.48971165883586,Actual: 520
Model: 233.98750288481097,Actual: 712
Model: 5635.734114380987,Actual: 7592
Model: 187.34994963022382,Actual: 855
Model: -436.4781932687615,Actual: 447
Model: 1369.7769456588749,Actual: 974
Model: 1336.2930551520867,Actual: 1181
Model: 10428.256199162493,Actual: 12509
Model: 2132.896904164083,Actual: 1819
Model: 5505.288080062837,Actual: 3760
Model: 655.1550437195428,Actual: 956
Model: 1554.0730786342756,Actual: 1624
Model: 2487.6257285824895,Actual: 2460
Model: -19.99254726965455,Actual: 457
Model: 4255.67967858788,Actual: 3348
Model: 5855.663946731966,Actual: 6765
Model: 5005.538116459167,Actual: 4963
Model: 3407.4631882834187,Actual: 4029
Model: 298.9537543858005,Actual: 791
Model: 5484.703157042494,Actual: 4967
Model: 1591.925791399431,Actual: 1439
Model: 686.5286830986947,Actual: 849
Model: 2996.4821427713377,Actual: 2303
Model: 4892.517463081534,Actual: 3920
Model: 7233.108743900169,Actual: 12253
Model: 10533.15719680958,Actual: 13085
Model: 1280.469754537698,Actual: 1289
Model: 2491.3369713816674,Actual: 2398
Model: 1178.4045902197468,Actual: 828
Model: 11643.181498302496,Actual: 15917
Model: 1289.7907326970894,Actual: 1166
Model: 353.1137847689811,Actual: 682
Model: 3631.37539679549,Actual: 3810
Model: 4879.151009579595,Actual: 4730
Model: 7868.712852241792,Actual: 8736
Model: 341.24095560082105,Actual: 575
Model: 3634.8790657646905,Actual: 2799
Model: 2475.0085749825157,Actual: 2290
Model: 3385.3759135500795,Actual: 2818
Model: 357.5471517108949,Actual: 810
Model: 6470.052689693827,Actual: 6046
Model: 8192.394341464198,Actual: 6300
Model: 93.89716917897749,Actual: 605
Model: 4390.054569986609,Actual: 3907
Model: 7700.455104994047,Actual: 6712
Model: 6733.917175265087,Actual: 12098
Model: 6007.2677549873,Actual: 5386
Model: 4663.697585586317,Actual: 5067
Model: 5159.641139555581,Actual: 6346
Model: 5241.935432702168,Actual: 7164
Model: 5307.19622783902,Actual: 5532
Model: 6938.796610210526,Actual: 9073
Model: 3783.201921417996,Actual: 1787
Model: 1952.866649719969,Actual: 1871
Model: 2229.5804208318027,Actual: 1901
Model: 1083.9409473490396,Actual: 863
Model: 3648.885721621679,Actual: 3447
Model: 2466.793906911749,Actual: 1970
Model: 1586.328223756475,Actual: 1412
Model: 2870.4609735209447,Actual: 2400
Model: 5999.810231711674,Actual: 6969
Model: 15829.32302411611,Actual: 17209
Model: 2304.7927305890826,Actual: 2056
Model: 8872.871232329213,Actual: 11284
Model: 613.1739330984092,Actual: 780
Model: 3760.3276884004263,Actual: 3672
Model: 1167.8843652361315,Actual: 1153
Model: 6087.940371343242,Actual: 2862
Model: 138.24218285386678,Actual: 626
Model: 3066.2298846362405,Actual: 2596
Model: 1956.465819835435,Actual: 1794
Model: 7897.5121491790815,Actual: 8969
Model: 354.73571587608467,Actual: 756
Model: 3269.9491549581744,Actual: 2863
Model: 4652.2447510139045,Actual: 4265
Model: 1927.2176496246511,Actual: 1433
Model: -510.66818784289126,Actual: 422
Model: 3051.848028973702,Actual: 2927
Model: 5537.087803229714,Actual: 7465
Model: 574.1190767436437,Actual: 807
Model: 1513.4371726361828,Actual: 1143
Model: 7331.76193404141,Actual: 11601
Model: 3023.7515759451267,Actual: 2193
Model: 5210.8847921450615,Actual: 4770
Model: 5117.422675358816,Actual: 6944
Model: 10446.123798709496,Actual: 18430
Model: 3031.0095497782513,Actual: 2581
Model: -244.4901350180171,Actual: 462
Model: 3134.2229019467613,Actual: 2961
Model: 4113.910081350616,Actual: 3119
Model: 3185.1255609535124,Actual: 3172
Model: 1900.4658934457595,Actual: 2243
Model: 1011.4893594092973,Actual: 1041
Model: 2463.0793080686512,Actual: 2208
Model: 1196.7067798336675,Actual: 853
Model: 3818.986136296426,Actual: 3326
Model: 609.1743906654251,Actual: 548
Model: 9060.382870079535,Actual: 11455
Model: 4423.964764782798,Actual: 4304
Model: 312.88778171647346,Actual: 504
Model: -370.4626126317744,Actual: 540
Model: 339.4351729159166,Actual: 844
Model: -600.171431117164,Actual: 369
Model: 2143.8284740535364,Actual: 1774
Model: 466.4696269256442,Actual: 734
Model: 13341.357731658125,Actual: 18432
Model: 4954.581847359092,Actual: 5759
Model: 228.3115574979165,Actual: 802
Model: 2104.1146152810297,Actual: 1906
Model: 2683.3390621607964,Actual: 2513
Model: 1688.9323975522157,Actual: 1154
Model: 7463.418823403326,Actual: 8624
Model: 3992.372890929206,Actual: 5502
Model: 2787.446224152747,Actual: 2263
Model: 1273.9922975396962,Actual: 1012
Model: 2552.2771825770005,Actual: 2202
Model: 3640.9023070600883,Actual: 3061
Model: 1557.247010196661,Actual: 1186
Model: 3246.011825684557,Actual: 2630
Model: 1614.0432150769498,Actual: 1629
Model: 499.4118387095168,Actual: 911
Model: 7447.361946061083,Actual: 11455
Model: 2635.851714415898,Actual: 2456
Model: 120.87601104952364,Actual: 477
Model: 1860.951929565921,Actual: 1407
Model: 3371.2327538811037,Actual: 2167
Model: 3451.0140972389063,Actual: 3101
Model: 1875.4030329571062,Actual: 2333
Model: 749.227016178525,Actual: 671
Model: 471.2951934345374,Actual: 702
Model: 598.7179261090241,Actual: 622
Model: 1460.868906040033,Actual: 1546
Model: 5894.037404592032,Actual: 6379
Model: 2334.065613915283,Actual: 2117
Model: 755.4219114370503,Actual: 965
Model: 9801.429440626187,Actual: 14860
Model: 1806.1761054636124,Actual: 1683
Model: 295.5705651754047,Actual: 645
Model: 6290.220471392564,Actual: 4509
Model: 8347.49810650674,Actual: 8997
Model: 1740.2183131140453,Actual: 1422
Model: -3.5302124761101368,Actual: 477
Model: -1029.9154770431073,Actual: 1186
Model: 1815.7162750940847,Actual: 1656
Model: 6954.351722860289,Actual: 9698
Model: 6098.288450648824,Actual: 4878
Model: 3937.4314861126313,Actual: 3923
Model: 1787.7641043255132,Actual: 1595
Model: 1975.832510292,Actual: 1787
Model: 983.5406559575795,Actual: 1050
Model: 1467.4016417935354,Actual: 1287
Model: 3316.548532391327,Actual: 2999
Model: 8039.572446602471,Actual: 7955
Model: 4820.451096155848,Actual: 4118
Model: 1866.877430946307,Actual: 1838
Model: 7772.643100338164,Actual: 10378
Model: 2221.5542662524977,Actual: 1629
Model: 6970.636384625892,Actual: 12261
Model: 10722.132560953532,Actual: 13134
Model: 813.3931946330881,Actual: 957
Model: 10015.091674645262,Actual: 18107
Model: 1918.527226967231,Actual: 1813
Model: 8740.169118821934,Actual: 13163
Model: 5217.202598018141,Actual: 5210
Model: 359.6266434970712,Actual: 737
Model: 1730.0079929077672,Actual: 1050